---
apiVersion: v1
kind: Secret
metadata:
  name: ${{ values.component_id }}-repo
  namespace: ${{ values.argocd_namespace }}
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: ${{ values.destination }}